name: "queryEmbed" 
platform: "ensemble"
max_batch_size: 16

input [
    {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: [ -1 ]
    },
    {
        name: "attention_mask"
        data_type: TYPE_INT64
        dims: [ -1 ]
    },
    {
        name: "token_type_ids"
        data_type: TYPE_INT64
        dims: [ -1 ]
    }
]
output [
    {
        name: "dense_embedding"
        data_type: TYPE_FP32
        dims: [ 768 ]
    },
    {
        name: "sparse_embedding"
        data_type: TYPE_FP32
        dims: [2,512]
    }

]
ensemble_scheduling{
    step [
        {
            model_name: "denseQueryEmbed"
            model_version: -1
            input_map {
                key: "input_ids"
                value: "input_ids"
            }
            input_map {
                key: "token_type_ids"
                value: "token_type_ids"
            }
            input_map {
                key: "attention_mask"
                value: "attention_mask"
            }
            output_map {
                key: "last_hidden_state"
                value: "dense_embedding"
            }
        },
        {
            model_name: "sparseQueryEmbedEngine"
            model_version: -1
            input_map {
                key: "input_ids"
                value: "input_ids"
            }
            input_map {
                key: "token_type_ids"
                value: "token_type_ids"
            }
            input_map {
                key: "attention_mask"
                value: "attention_mask"
            }
            output_map {
                key: "sparse_embeddings"
                value: "sparse"
            }
        },
        {
            model_name: "sparseResults"
            model_version: -1
            input_map {
                key: "INPUT0"
                value: "sparse"
            }
            output_map {
                key: "OUTPUT0"
                value: "sparse_embedding"
            }
        }
    ]
}
