version: '3.8'
services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    network_mode: "host"
    volumes:
      - type: bind
        source: /home/op3ntrap/Repos/CatalogONDC/model_repository
        target: /models
    command: tritonserver --model-repository=/models --model-control-mode=poll --repository-poll-secs=20 --exit-on-error true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mongodb:
    image: mongo:7.0.5-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel nothing
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data

configs:
  qdrant_config:
    content: |
            log_level: INFO


volumes:
  mongodb_data:
  redis_data:
  qdrant_data:
